### ISSUE TITLE
Bug: 계정 중복 username 생성 가능, 계정 간 프로필 이름 중복 생성 불가능

### ISSUE THREAD

**Issue by dkdud9261** [among-neighbors/AN-backend#88]
1. Postman 으로 계정 생성을 진행하던 도중 중복으로 username 을 가지는 계정을 생성할 수 있다는 것을 확인하였습니다.
2. 서로 다른 계정에 같은 이름의 프로필을 생성 가능해야 하지만 현재 불가능 합니다.

**Comment by PPakSang** [comment]
수정 완료
